// ============================================================
// ShowPilot-Lite — Configuration
// All config values live at the top for easy editing.
//
// Lite is the FPP-side build of ShowPilot — runs on the same host
// as Falcon Player and provides voting / jukebox / now-playing
// display. Audio streaming is removed (FPP's SD card can't take
// the I/O); pair with PulseMesh / FM / Icecast for audio delivery.
// ============================================================

module.exports = {
  // Server
  port: 3100,
  host: '0.0.0.0',

  // ============================================================
  // Reverse proxy / "trust proxy"
  // ============================================================
  // ShowPilot-Lite uses the client IP for several things: rate limiting
  // login attempts, blocking abusive viewers, and recording visitor
  // analytics. It's important the IP is real, not spoofed.
  //
  // - If you run ShowPilot-Lite directly exposed (port-forward, no proxy):
  //     trustProxy: false
  //   This makes Express ignore X-Forwarded-For headers entirely, so an
  //   attacker can't fake their IP by setting that header.
  //
  // - If you run ShowPilot-Lite behind a reverse proxy you control (Nginx
  //   Proxy Manager, Caddy, Traefik, Cloudflare Tunnel, etc.):
  //     trustProxy: 1
  //   This trusts X-Forwarded-For from exactly one upstream hop. Almost
  //   always correct for typical deployments — your proxy is the only thing
  //   that should be setting that header.
  //
  // - If you have a chain of proxies (CDN → load balancer → app):
  //     trustProxy: 2     // trust 2 hops
  //
  // - For CIDR-based trust (rarely needed):
  //     trustProxy: 'loopback, 192.168.0.0/16'
  //
  // Default: false (most secure — assume direct exposure).
  trustProxy: false,

  // Database
  dbPath: './data/showpilot-lite.db',

  // ============================================================
  // Auth secrets — auto-generated by default
  // ============================================================
  // jwtSecret signs admin session cookies. showToken is what the FPP
  // plugin sends in its `Authorization: Bearer ...` header.
  //
  // Default behavior (null values): both are auto-generated on first
  // startup using crypto.randomBytes(32) and persisted to
  // data/secrets.json. This is the recommended path — the generated
  // values are 256-bit random hex, much stronger than anything you'd
  // type by hand.
  //
  // To set your own values manually, replace null with a real string:
  //   jwtSecret: 'your-very-long-random-string-here',
  //   showToken: 'your-fpp-plugin-token-here',
  //
  // To override via environment variables (good for Docker/Kubernetes):
  //   SHOWPILOT_JWT_SECRET=...
  //   SHOWPILOT_SHOW_TOKEN=...
  // Env vars take precedence over both config.js values and
  // auto-generated values.
  //
  // To rotate auto-generated secrets: delete data/secrets.json, then
  // restart. New values will be generated. Note: this invalidates all
  // existing admin sessions and forces an FPP plugin reconfiguration.
  jwtSecret: null,
  sessionCookieName: 'showpilot_lite_session',
  sessionDurationHours: 24 * 30, // 30 days

  showToken: null,

  // Viewer behavior
  viewer: {
    // How long a viewer heartbeat is considered "active" (seconds)
    activeWindowSeconds: 30,
    // How often viewer page polls for state updates (ms) as a fallback if socket fails
    pollIntervalMs: 5000,
    // Max jukebox requests per viewer token per night
    maxJukeboxRequestsPerViewer: 1,
    // Max votes per viewer per voting round
    maxVotesPerRound: 1,
  },

  // Voting round behavior
  voting: {
    // Auto-reset votes after the winner plays? (typical setup)
    resetAfterWinnerPlays: true,
  },

  // Logging
  logLevel: 'info', // 'debug' | 'info' | 'warn' | 'error'
};
