#!/bin/bash
# ============================================================
# ShowPilot-Lite — FPP plugin install script
# ============================================================
# FPP runs this after `git clone`-ing the plugin into
# /home/fpp/media/plugins/ShowPilot-Lite/. It must:
#   1. Ensure Node 18+ is available (install via NodeSource if not)
#   2. Set up the data directory (under FPP's plugindata, so FPP backups capture it)
#   3. Write a config.js if one doesn't exist
#   4. Compile native deps via `npm install --omit=dev`
#   5. Install + enable a systemd unit so it starts on boot
#   6. Start the service
#
# Idempotent: re-running after a plugin update should be safe. We
# only do destructive steps (overwriting config) when the file is
# missing.
#
# Errors here are visible in FPP's plugin manager output. We `set -e`
# so the install fails loudly rather than silently — better for the
# user to see "Node install failed" than to find ShowPilot-Lite
# silently broken later.
# ============================================================

set -e

PLUGIN_DIR="/home/fpp/media/plugins/ShowPilot-Lite"
DATA_DIR="/home/fpp/media/plugindata/ShowPilot-Lite"
SERVICE_NAME="showpilot-lite"
SERVICE_FILE="/etc/systemd/system/${SERVICE_NAME}.service"

echo "============================================================"
echo "ShowPilot-Lite install"
echo "============================================================"
echo "Plugin dir:  $PLUGIN_DIR"
echo "Data dir:    $DATA_DIR"
echo

# ---------------------------------------------------------------
# 1. Node 18+ check / install
# ---------------------------------------------------------------
NEED_NODE_INSTALL=0
if ! command -v node >/dev/null 2>&1; then
    echo "[install] Node not found — will install Node 18 from NodeSource"
    NEED_NODE_INSTALL=1
else
    NODE_MAJOR=$(node -v | sed 's/^v\([0-9]*\).*/\1/')
    if [ "$NODE_MAJOR" -lt 18 ] 2>/dev/null; then
        echo "[install] Node $(node -v) is too old (need 18+) — will upgrade"
        NEED_NODE_INSTALL=1
    else
        echo "[install] Node $(node -v) — OK"
    fi
fi

if [ "$NEED_NODE_INSTALL" = "1" ]; then
    # NodeSource setup script handles the apt repo + key. We pipe through
    # bash directly because that's the upstream-recommended idiom and
    # FPP plugin installs are already running with elevated privileges.
    echo "[install] Adding NodeSource apt repo for Node 18.x..."
    curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -
    echo "[install] Installing nodejs..."
    sudo apt-get install -y nodejs
    echo "[install] Installed: $(node -v)"
fi

# ---------------------------------------------------------------
# 2. Data directory
# ---------------------------------------------------------------
# Strategy: keep the application's hardcoded ./data/ path, but make
# it a symlink into FPP's plugindata. This way:
#   - cover-art.js (which uses path.join(__dirname,'..','data','covers')) works unchanged
#   - DB, covers, secrets all live under plugindata
#   - FPP backups capture everything (FPP backs up plugindata)
#   - Reinstalling the plugin doesn't wipe the user's data (only the
#     plugin source dir is re-cloned; the symlink target survives)
echo "[install] Ensuring data dir exists: $DATA_DIR"
sudo mkdir -p "$DATA_DIR"
sudo mkdir -p "$DATA_DIR/covers"
sudo chown -R fpp:fpp "$DATA_DIR"

# If the plugin dir has a real ./data/ directory from a prior non-symlink
# install or a stray git checkout, migrate its contents into plugindata
# before symlinking. Otherwise just create the symlink.
if [ -d "$PLUGIN_DIR/data" ] && [ ! -L "$PLUGIN_DIR/data" ]; then
    echo "[install] Migrating existing $PLUGIN_DIR/data/ contents into $DATA_DIR..."
    # Copy with -a to preserve perms, then drop the original.
    sudo cp -a "$PLUGIN_DIR/data/." "$DATA_DIR/"
    sudo rm -rf "$PLUGIN_DIR/data"
fi

# Create or refresh the symlink. -n stops `ln -sf` from following an
# existing symlink and creating the new link inside the target dir.
sudo ln -snf "$DATA_DIR" "$PLUGIN_DIR/data"
sudo chown -h fpp:fpp "$PLUGIN_DIR/data"

# ---------------------------------------------------------------
# 3. Config file
# ---------------------------------------------------------------
CONFIG_FILE="$PLUGIN_DIR/config.js"
if [ -f "$CONFIG_FILE" ]; then
    echo "[install] config.js already exists — leaving it alone"
else
    echo "[install] Writing initial config.js (dbPath -> ./data via symlink to $DATA_DIR)"
    # The dbPath uses the in-tree ./data/ path, which is now a symlink to
    # the FPP-managed plugindata location. Keeps cover-art.js happy
    # (it joins __dirname to 'data') while putting actual files under
    # plugindata where FPP's backup feature finds them.
    cat > "$CONFIG_FILE" <<EOF
// ============================================================
// ShowPilot-Lite — host-specific configuration
// Generated by FPP plugin installer.
//
// dbPath is './data/showpilot-lite.db' but ./data is a symlink to
// /home/fpp/media/plugindata/ShowPilot-Lite — see fpp_install.sh.
// ============================================================
module.exports = {
  port: 3100,
  host: '0.0.0.0',
  trustProxy: false,

  dbPath: './data/showpilot-lite.db',

  // Secrets auto-generate on first boot, persisted to data/secrets.json
  jwtSecret: null,
  sessionCookieName: 'showpilot_lite_session',
  sessionDurationHours: 24 * 30,
  showToken: null,

  viewer: {
    activeWindowSeconds: 30,
    pollIntervalMs: 5000,
    maxJukeboxRequestsPerViewer: 1,
    maxVotesPerRound: 1,
  },
  voting: {
    resetAfterWinnerPlays: true,
  },
  logLevel: 'info',
};
EOF
    sudo chown fpp:fpp "$CONFIG_FILE"
fi

# ---------------------------------------------------------------
# 4. npm install (compiles better-sqlite3 against host Node)
# ---------------------------------------------------------------
echo "[install] Running npm install --omit=dev (this may take a minute)..."
cd "$PLUGIN_DIR"
sudo -u fpp npm install --omit=dev --no-audit --no-fund

# ---------------------------------------------------------------
# 5. systemd unit
# ---------------------------------------------------------------
echo "[install] Writing systemd unit: $SERVICE_FILE"
sudo tee "$SERVICE_FILE" >/dev/null <<EOF
[Unit]
Description=ShowPilot-Lite (FPP-resident voting / jukebox / now-playing display)
After=network.target fppd.service
Wants=network.target

[Service]
Type=simple
User=fpp
Group=fpp
WorkingDirectory=${PLUGIN_DIR}
ExecStart=/usr/bin/node ${PLUGIN_DIR}/server.js
Restart=on-failure
RestartSec=5
StandardOutput=append:/home/fpp/media/logs/showpilot-lite.log
StandardError=append:/home/fpp/media/logs/showpilot-lite.log

[Install]
WantedBy=multi-user.target
EOF

echo "[install] Reloading systemd, enabling + starting service..."
sudo systemctl daemon-reload
sudo systemctl enable "$SERVICE_NAME"
sudo systemctl restart "$SERVICE_NAME"

# Give it a beat to come up, then check status
sleep 2
if sudo systemctl is-active --quiet "$SERVICE_NAME"; then
    echo
    echo "============================================================"
    echo "ShowPilot-Lite is running."
    echo "============================================================"
    echo "Open from FPP's Content Setup menu, or directly at:"
    echo "    http://$(hostname -I | awk '{print $1}'):3100/"
    echo
    echo "Default login: admin / admin (you'll be prompted to change)"
    echo "Logs:    /home/fpp/media/logs/showpilot-lite.log"
    echo "Service: systemctl status $SERVICE_NAME"
    echo "============================================================"
else
    echo
    echo "[install] WARNING: $SERVICE_NAME did not start cleanly."
    echo "[install] Check logs: journalctl -u $SERVICE_NAME -n 50"
    exit 1
fi
